spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: proe
eureka:
  client:   #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: proe8001
    prefer-ip-address: true       #访问路径可以显示ip地址
info:
  app.name: cloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: proe
eureka:
  client:   #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: proe8001
    prefer-ip-address: true       #访问路径可以显示ip地址
info:
  app.name: cloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$